### ISSUE TITLE
Code style questions

### ISSUE THREAD

**Issue by daniillnull** [XeonDevv/JavaBrawl#1]
As I can see this server is based on my leaked CRServer 2016 (that is fully draft/dirty/shitty code). Why don't you want to think by yourself and create good architecture instead of copying bad one?🤡

**Comment by XeonDevv** [comment]
Just die with cancer pls

**Comment by daniillnull** [comment]
Argumented answer👍
Don't think that impermissible behavior and insults will justify your code quality.
